// SPDX-FileCopyrightText: © 1995-1996 Jan Hubicka
// SPDX-FileCopyrightText: © 1995-1996 Kamil Toman
// SPDX-FileCopyrightText: © 1995-1996 Thomas Marsh
// SPDX-FileCopyrightText: © 2026 Mesmotronic Limited
// SPDX-License-Identifier: GPL-2.0-or-later

/**
 * The scroller scripts from `text.h`, by Kamil Toman and Jan Hubicka.
 *
 * Two lines in the original array were missing a comma and so were joined by
 * the C preprocessor. They are kept joined here, because `intro.c` indexes
 * this array by line number to cue the animation (see {@link KOULES_LINE} and
 * friends) and splitting them would desynchronise every cue.
 */

/** Cue: the ring of koules collapses into view. */
export const KOULES_LINE = 11;
/** Cue: the player's ship materialises. */
export const PLAYER_LINE = 34;
/** Cue: the first deserter koule starts its approach. */
export const D1_LINE = 44;
/** Cue: the second deserter follows. */
export const D2_LINE = 46;
/** Cue: the B_BALL rises from the bottom of the screen. */
export const B_LINE = 57;

/** The opening crawl. */
export const introCrawl: readonly string[] = [
	'Somewhere in the galaxy',
	'...',
	'Once upon a time',
	'the evil',
	'KOULES',
	'exhausted all the resources',
	'of their home planet',
	'...',
	'Their emperor',
	'THE DARK APPLEPOLISHER',
	'deployed his brutal',
	'hyperspace commandos',
	'to wipe out',
	'a human civilization',
	"and claim Earth's",
	'resources for his',
	'realms...',
	'The nations of Earth',
	'chose their best warriors',
	'to defend our planet',
	'...',
	'These champions were',
	'biologically mutated',
	'into special creatures.',
	'Their entities were reduced',
	'to mere chests and eyes',
	'...',
	'These qualities allow them',
	"operate in enemies' domain",
	'...',
	'Your battle for a new world',
	'begins',
	'',
	'NOW',
	'...',
	'Your mission is to',
	'bounce all',
	'KOULES fighters',
	'from your sector',
	'...',
	'Some of them are',
	'deserters',
	'The green ones give you',
	'acceleration',
	'the blue ones give you',
	'more weight',
	'...',
	'Look out',
	'for',
	'mighty',
	'super-spherical',
	'megaheavy',
	'ultra green',
	'B_BALL',
	'...',
	'',
	'',
	'KOULES TEAM',
	'...',
	'Programming by Jan Hubicka',
	'...',
	'OS/2 version by Thomas A. K. Kjaer',
	'...',
	'Three.js port by Mesmotronic',
	'...',
	'Script by Kamil Toman',
	'and Jan Hubicka',
	'...',
	'Spelling check by Thomas Marsh',
	'...',
	'Graphics by Jan Hubicka',
	'and Kamil Toman',
	'...',
	'Sounds by Jan Hubicka',
	'...',
	'HP-UX sound by Lutz Vieweg',
	'...',
	'SGI sound by Rick Sayre',
	'...',
	'Story by Kamil Toman',
	'and Jan Hubicka',
	'...',
	'Sound server by',
	'Joe Rumsey',
	'and S. M. Patel',
	'...',
	'Joystick support by',
	'Ludvik Tesar',
	'...',
	'SDL version by Lubomir Rintel',
	'...',
	'Greetings',
	'...',
	'Linus Torvalds',
	'Have a nice Linux',
	'...',
	'Ondrej Stasek',
	'alias KOTELNIK',
	'from RDOS',
	'Hello you ___',
	'nice man',
	'...',
	'Jaroslav Kysela',
	'debugged on your GUS driver',
	'...',
	'Mojmir Svoboda',
	'No chance to run it',
	'on your machine...',
	"It doesn't matter",
	"you've bought better",
	'computer equipment',
	'...',
	'Roman Zenka',
	'You lucky man',
	'you ARE in credits',
	'...',
	'Aragorn',
	'Thanks for an account',
	'...',
	'Jaroslav Pech',
	'When could I hope you learn',
	'Linux',
	'...',
	'Roman Dolejsi',
	'I hope your game',
	'will be better',
	'...',
	'Boris Letocha',
	'Write me in credits in',
	'your game',
	'...',
	'...',
	'HEY WAKE UP',
	'and',
	'press any key',
	'excluding',
	'power',
	'reset',
	'turbo',
	'CTRL+C',
	'CTRL+Z',
	'ALT F1',
	'ALT F2',
	'ALT F3',
	'ALT F4',
	'ALT F5',
	'ALT F6',
	'ALT F7',
	'ALT F8',
	'ALT F9',
	'ALT F10',
	'ALT F11',
	'ALT F12',
	'ALT F13',
	'( huh )',
	'...',
	'ALT LEFT ARROW',
	'ALT RIGHT ARROW',
	'ESC',
	'and some other',
	'keys',
	'( no key except A is safe )...',
	'Copyright(c)1995-1996',
	'Jan Hubicka',
	'hubicka@paru.cas.cz'
];

/** `text1` — shown on entering the final sector. */
export const outro1Crawl: readonly string[] = [
	'Very well',
	'...',
	'You have destroyed most',
	'of the Koules fighters',
	'...',
	'Now you are',
	'in the main base',
	'Your goal',
	'is to destroy the',
	'Mighty',
	'Mega',
	'Super',
	'Ultra',
	'HEAVY',
	'DARK APPLEPOLISHER'
];

/** `text2` — the ending. */
export const outro2Crawl: readonly string[] = [
	'Congratulations',
	'your mission is complete',
	'...',
	'The death of',
	'DARK APPLEPOLISHER',
	'caused the end',
	'of the whole',
	'KOULES civilization',
	'...',
	'Millions of',
	'innocent KOULES',
	'died in chaos',
	'caused by death',
	'of DARK APPLEPOLISHER',
	'...',
	'You have killed',
	'innocent KOULES',
	'You killer',
	'You murderer',
	'You...you..you..',
	'...',
	'And now',
	'Wait for',
	'The greatest',
	'Game',
	'For',
	'Linux',
	'...',
	'KOULES II',
	'...',
	''
];

/** The sector briefings, keyed by the names `GamePlan` emits. */
export const briefings: Readonly<Record<string, readonly string[]>> = {

	intro: [
		'The best way',
		'to play KOULES',
		'is to let you play',
		'without instructions',
		'...',
		'We can only advise you',
		'...',
		'(connection failed)'
	],

	hole: [
		'Our scientists have',
		'developed a great',
		'weapon',
		'so powerful',
		'that even you can',
		'be destroyed by it',
		'...',
		'They have designed',
		'special black holes',
		'which can be moved',
		'through the hyperspace',
		'Your advantage is',
		'that black holes cannot',
		'be seen by KOULES'
	],

	inspector: [
		'Standard KOULES',
		'inspectors were sent',
		'to monitor your actions',
		'They can not be destroyed',
		'directly',
		'...',
		'Good luck',
		'...'
	],

	bball: [
		'The DARK APPLEPOLISHER',
		'has heard about you',
		'You are famous',
		'This has one disadvantage',
		'B_BALLS are going to',
		'kick you out',
		'of the game',
		'We believe in your',
		'abilities',
		'Yet no one had survived',
		'the ... meeting ...',
		'before'
	],

	bbball: [
		'You entered the',
		'PRIMARY ALARM ZONE',
		'New B_BALLS have been',
		'sent to protect the leader',
		'...',
		'do not',
		'turn the power off',
		'you are near',
		'your goal',
		'NOW you can finish the game'
	],

	maghole: [
		'KOULES are not stupid',
		'They have developed a new',
		'funny weapon',
		'which can be called',
		'the MAGNETIC HOLE',
		'...'
	],

	spring: [
		'Koules have',
		'more hidden qualities',
		'...',
		"When they're in a danger",
		'they spit on you',
		'...',
		'their spits sticks to you',
		'...',
		'Do not puke on the keyboard',
		'...'
	],

	thief: [
		'During the war',
		"the Earth's power",
		'resources have been',
		'almost exhausted',
		'...',
		'An underground guerilla',
		'organisation called SUBWAY',
		'was established',
		'to take care',
		'of this problem',
		'...',
		'SUBWAY squads',
		'known as Thieves',
		'managed to infiltrate',
		'war teritories',
		'...'
	],

	finder: [
		'Their competitors,',
		'the on-the-ground',
		'organisation SURFACE',
		'developed a special',
		'persuaduing method',
		'which makes',
		'a Thief become',
		'a complete boob',
		'which returns to you',
		'everything he has stolen',
		'...',
		'Technical note',
		'This technology',
		'is based on UNIX',
		'lost+found directory'
	],

	ttool: [
		'After intensive',
		'research our scientists',
		'have finally stolen',
		"SUBWAY's technologies",
		'...',
		'If you get a special',
		'chip you will be able',
		'to steal energy',
		'from other ships or B_BALLS'
	],

	lunatic: [
		' DANGER ',
		'Our scientists',
		'have been working',
		'on very dangerous',
		'virus',
		'...',
		'By a small mistake',
		'they left the',
		'laboratory',
		'open and have',
		'accidentally released',
		'the LUNATICS.',
		'...',
		'Beware, for Lunatics',
		'are extremely',
		'dangerous.'
	],

	outro1: outro1Crawl

};

/** The help captions `koules.c` drew beside each object with H held down. */
export const HELP_TEXT: Readonly<Record<string, string>> = {
	ball: 'Koules',
	accel: 'Acceleration',
	gumm: 'Weight',
	thief: 'Thief',
	finder: 'Goodie',
	ttool: 'Thief toolkit',
	hole: 'Black hole',
	ehole: 'Magnetic hole',
	bball: 'BBALL!',
	inspector: 'Inspector',
	lunatic: 'Lunatic',
	apple: 'APPLEPOLISHER',
	rocket: 'Player',
	spring: 'Spit'
};
